startuml
left to right direction
actor Cliente
actor Agente as "Agente (Empresa/Banco)"
actor ServidorCentral

rectangle "Sistema de Aluguel de Automóveis" {
    usecase "Cadastro/Autenticação" as UC1
    usecase "Gerenciar pedido de aluguel" as UC2
    usecase "Analisar Pedido Financeiramente" as UC6
    usecase "Modificar Pedido" as UC7
    usecase "Executar Contrato de Aluguel" as UC9
    usecase "Gerenciar Automóveis" as UC10
}

Cliente -- UC1
Cliente -- UC2

Agente -- UC6
Agente -- UC7


UC6 <- UC7 
UC9 <- UC6 : <<extends>>

ServidorCentral --> UC9
ServidorCentral --> UC10
@enduml
