@startuml

component "Interface Rent car system" as interfaceLayer
' Camada API
component "API Rent car system " as apiLayer

interfaceLayer --> apiLayer
' SQL Servers
database "SGBD" as sql

' Organizando as conexões de interfaces
apiLayer -down-( tcp
tcp -down- sql

@enduml