@startuml
package "Beans" {
}

package "Controllers" {
}

package "DAO" {
}

package "Enums" {
}

package "Exceptions" {
}

package "model" {
}

package "Repository" {
}

package "Service" {
}

package "Resources" {
}

package "WebApp" {
}

package "Src" {
}
"Autenticação" -> "Cliente"
"Agente" -> "Pedido"
"Pedido" -> "Veiculo"
"Pedido" -> "Contrato"
"Contrato" -> "ContratoCredito"
"Cliente" -> "Empregador"
@enduml
