@startuml
package "Autenticação" {
}

package "Cliente" {
}

package "Agente" {
}

package "Empregador" {
}

package "Pedido" {
}

package "Veiculo" {
}

package "Contrato" {
}

package "ContratoCredito" {
}

"Autenticação" -> "Cliente"
"Agente" -> "Pedido"
"Pedido" -> "Veiculo"
"Pedido" -> "Contrato"
"Contrato" -> "ContratoCredito"
"Cliente" -> "Empregador"
@enduml
